[2024-07-20T18:09:59.603+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v01.greet manual__2024-07-20T18:09:56.061939+00:00 [queued]>
[2024-07-20T18:09:59.616+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v01.greet manual__2024-07-20T18:09:56.061939+00:00 [queued]>
[2024-07-20T18:09:59.617+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-20T18:09:59.643+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): greet> on 2024-07-20 18:09:56.061939+00:00
[2024-07-20T18:09:59.651+0000] {standard_task_runner.py:57} INFO - Started process 12858 to run task
[2024-07-20T18:09:59.658+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v01', 'greet', 'manual__2024-07-20T18:09:56.061939+00:00', '--job-id', '1086', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpe1f70x5i']
[2024-07-20T18:09:59.666+0000] {standard_task_runner.py:85} INFO - Job 1086: Subtask greet
[2024-07-20T18:09:59.746+0000] {task_command.py:416} INFO - Running <TaskInstance: our_dag_with_python_operator_v01.greet manual__2024-07-20T18:09:56.061939+00:00 [running]> on host b8647d758ea8
[2024-07-20T18:09:59.926+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v01' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T18:09:56.061939+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-20T18:09:56.061939+00:00'
[2024-07-20T18:09:59.929+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    name = ti.xcoms_pull(task_ids='get_name')
AttributeError: 'TaskInstance' object has no attribute 'xcoms_pull'
[2024-07-20T18:09:59.948+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v01, task_id=greet, execution_date=20240720T180956, start_date=20240720T180959, end_date=20240720T180959
[2024-07-20T18:09:59.976+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1086 for task greet ('TaskInstance' object has no attribute 'xcoms_pull'; 12858)
[2024-07-20T18:10:00.002+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-20T18:10:00.025+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
