[2024-07-23T13:54:17.773+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_minio.sensor_minio_s3 manual__2024-07-22T23:26:25.157059+00:00 [queued]>
[2024-07-23T13:54:17.957+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_minio.sensor_minio_s3 manual__2024-07-22T23:26:25.157059+00:00 [queued]>
[2024-07-23T13:54:17.959+0000] {taskinstance.py:1361} INFO - Starting attempt 15 of 15
[2024-07-23T13:54:17.985+0000] {taskinstance.py:1382} INFO - Executing <Task(S3KeySensor): sensor_minio_s3> on 2024-07-22 23:26:25.157059+00:00
[2024-07-23T13:54:17.993+0000] {standard_task_runner.py:57} INFO - Started process 2328 to run task
[2024-07-23T13:54:18.016+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_minio', 'sensor_minio_s3', 'manual__2024-07-22T23:26:25.157059+00:00', '--job-id', '1189', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_minio_s3.py', '--cfg-path', '/tmp/tmpr11c477z']
[2024-07-23T13:54:18.025+0000] {standard_task_runner.py:85} INFO - Job 1189: Subtask sensor_minio_s3
[2024-07-23T13:54:18.166+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_minio.sensor_minio_s3 manual__2024-07-22T23:26:25.157059+00:00 [running]> on host f777c2717f23
[2024-07-23T13:54:18.375+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='dag_with_minio' AIRFLOW_CTX_TASK_ID='sensor_minio_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-22T23:26:25.157059+00:00' AIRFLOW_CTX_TRY_NUMBER='15' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-22T23:26:25.157059+00:00'
[2024-07-23T13:54:18.377+0000] {s3.py:106} INFO - Poking for key : s3://***/data.csv
[2024-07-23T13:54:18.398+0000] {base.py:73} INFO - Using connection ID 'minio_s3_conn' for task execution.
[2024-07-23T13:54:18.400+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='minio_s3_conn', conn_type='aws') credentials retrieved from login and password.
[2024-07-23T13:54:19.297+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 144, in execute
    super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 257, in execute
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/sensors/base.py", line 239, in execute
    poke_return = self.poke(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 137, in poke
    return self._check_key(self.bucket_key)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/sensors/s3.py", line 125, in _check_key
    obj = self.hook.head_object(key, bucket_name)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 135, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 89, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 884, in head_object
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 879, in head_object
    return self.get_conn().head_object(Bucket=bucket_name, Key=key)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (403) when calling the HeadObject operation: Forbidden
[2024-07-23T13:54:19.388+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=dag_with_minio, task_id=sensor_minio_s3, execution_date=20240722T232625, start_date=20240723T135417, end_date=20240723T135419
[2024-07-23T13:54:19.412+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1189 for task sensor_minio_s3 (An error occurred (403) when calling the HeadObject operation: Forbidden; 2328)
[2024-07-23T13:54:19.487+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-23T13:54:19.523+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
