[2024-07-21T00:31:49.908+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T00:31:49.966+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T00:31:49.967+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-21T00:31:50.006+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): greet> on 2024-07-20 00:00:00+00:00
[2024-07-21T00:31:50.025+0000] {standard_task_runner.py:57} INFO - Started process 27745 to run task
[2024-07-21T00:31:50.072+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'greet', 'scheduled__2024-07-20T00:00:00+00:00', '--job-id', '1102', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmpcfwxc_x3']
[2024-07-21T00:31:50.078+0000] {standard_task_runner.py:85} INFO - Job 1102: Subtask greet
[2024-07-21T00:31:50.227+0000] {task_command.py:416} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [running]> on host b8647d758ea8
[2024-07-21T00:31:50.821+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-20T00:00:00+00:00'
[2024-07-21T00:31:50.824+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    first_name = ti.xcom_pull(task_id='get_name', key='first_name')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2024-07-21T00:31:50.848+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v05, task_id=greet, execution_date=20240720T000000, start_date=20240721T003149, end_date=20240721T003150
[2024-07-21T00:31:50.873+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1102 for task greet (xcom_pull() got an unexpected keyword argument 'task_id'; 27745)
[2024-07-21T00:31:50.975+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-21T00:31:51.025+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-21T00:39:04.093+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T00:39:04.167+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [queued]>
[2024-07-21T00:39:04.172+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-21T00:39:04.302+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): greet> on 2024-07-20 00:00:00+00:00
[2024-07-21T00:39:04.365+0000] {standard_task_runner.py:57} INFO - Started process 28030 to run task
[2024-07-21T00:39:04.488+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'our_dag_with_python_operator_v05', 'greet', 'scheduled__2024-07-20T00:00:00+00:00', '--job-id', '1106', '--raw', '--subdir', 'DAGS_FOLDER/create_dag_with_python_operator.py', '--cfg-path', '/tmp/tmphme4s9yj']
[2024-07-21T00:39:04.561+0000] {standard_task_runner.py:85} INFO - Job 1106: Subtask greet
[2024-07-21T00:39:04.983+0000] {task_command.py:416} INFO - Running <TaskInstance: our_dag_with_python_operator_v05.greet scheduled__2024-07-20T00:00:00+00:00 [running]> on host b8647d758ea8
[2024-07-21T00:39:06.242+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='our_dag_with_python_operator_v05' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-07-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-20T00:00:00+00:00'
[2024-07-21T00:39:06.246+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/create_dag_with_python_operator.py", line 14, in greet
    first_name = ti.xcom_pull(task_id='get_name', key='first_name')
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 79, in wrapper
    return func(*args, session=session, **kwargs)
TypeError: xcom_pull() got an unexpected keyword argument 'task_id'
[2024-07-21T00:39:06.497+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=our_dag_with_python_operator_v05, task_id=greet, execution_date=20240720T000000, start_date=20240721T003904, end_date=20240721T003906
[2024-07-21T00:39:06.570+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1106 for task greet (xcom_pull() got an unexpected keyword argument 'task_id'; 28030)
[2024-07-21T00:39:06.645+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-21T00:39:06.687+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
