[2024-07-23T16:36:55.947+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hook_v01.postgres_to_s3 manual__2024-07-23T16:36:53.222333+00:00 [queued]>
[2024-07-23T16:36:55.965+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hook_v01.postgres_to_s3 manual__2024-07-23T16:36:53.222333+00:00 [queued]>
[2024-07-23T16:36:55.966+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2024-07-23T16:36:56.077+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2024-07-23 16:36:53.222333+00:00
[2024-07-23T16:36:56.091+0000] {standard_task_runner.py:57} INFO - Started process 5198 to run task
[2024-07-23T16:36:56.111+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hook_v01', 'postgres_to_s3', 'manual__2024-07-23T16:36:53.222333+00:00', '--job-id', '1203', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_hook.py', '--cfg-path', '/tmp/tmpswan_hcm']
[2024-07-23T16:36:56.118+0000] {standard_task_runner.py:85} INFO - Job 1203: Subtask postgres_to_s3
[2024-07-23T16:36:56.401+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_hook_v01.postgres_to_s3 manual__2024-07-23T16:36:53.222333+00:00 [running]> on host 16388eb016bf
[2024-07-23T16:36:56.655+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Bowen' AIRFLOW_CTX_DAG_ID='dag_with_postgres_hook_v01' AIRFLOW_CTX_TASK_ID='postgres_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T16:36:53.222333+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T16:36:53.222333+00:00'
[2024-07-23T16:36:56.720+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2024-07-23T16:36:56.812+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgres_hook.py", line 25, in postgres_to_s3
    csv_writer = csv.writer()
TypeError:  expected at least 1 argument, got 0
[2024-07-23T16:36:56.850+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hook_v01, task_id=postgres_to_s3, execution_date=20240723T163653, start_date=20240723T163655, end_date=20240723T163656
[2024-07-23T16:36:56.907+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1203 for task postgres_to_s3 ( expected at least 1 argument, got 0; 5198)
[2024-07-23T16:36:56.933+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-23T16:36:56.969+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
